
export let FORM_BIBLIOTECA = {
    titulo: 'Biblioteca',
    tipo_formulario: 'mini',
    btn: 'Guardar',
    alertas: true,
    modelo: 'Biblioteca',
    campos: [
    {
        etiqueta: 'input',
        claseGrid: 'col-md-6',
        nombre: 'TipoClasificación',
        label_i18n: 'tipo_clasificación',
        placeholder_i18n: 'tipo_clasificación',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-md-6',
        nombre: 'Nombre',
        label_i18n: 'nombre',
        placeholder_i18n: 'nombre',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-md-6',
        nombre: 'Telefonos',
        label_i18n: 'telefonos',
        placeholder_i18n: 'telefonos',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'textarea',
        claseGrid: 'col-md-6',
        nombre: 'HorarioGeneral',
        label_i18n: 'horario_general',
        placeholder_i18n: 'horario_general',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-md-6',
        nombre: 'Fax',
        label_i18n: 'fax',
        placeholder_i18n: 'fax',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-md-6',
        nombre: 'SitioWeb',
        label_i18n: 'sitio_web',
        placeholder_i18n: 'sitio_web',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-md-6',
        nombre: 'Correo',
        label_i18n: 'correo',
        placeholder_i18n: 'correo',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-md-6',
        nombre: 'Direccion',
        label_i18n: 'direccion',
        placeholder_i18n: 'direccion',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-md-6',
        nombre: 'CordX',
        label_i18n: 'cord_x',
        placeholder_i18n: 'cord_x',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-md-6',
        nombre: 'CordY',
        label_i18n: 'cord_y',
        placeholder_i18n: 'cord_y',
        requerido: true,
        tipo: 'number',
    },
    ],
}
